BootPress/Models/News.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BootPress.Models
{
    public class News
    {
        [Key]
        public string Permalink { get; set; }
        public Category Category { get; set; }
        public string Title { get; set; }
        [AllowHtml]
        public string Hightlight { get; set; }
        [AllowHtml]
        public string Content { get; set; }
        public DateTimeOffset Created { get; set; }
        public Status Status { get; set; }
        public ApplicationUser Author { get; set; }
        public bool IsDeleted { get; set; }
        public DateTimeOffset Updated { get; set; }
        public double Price { get; set; }
    }
    public class Category
    {
        [Key]
        public string IdCategory { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
    public enum Status
    {
        Published,
        Draft,
        Review
    }
}

BootPress/Controllers/AdministratorsController.cs
using BootPress.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BootPress.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdministratorsController : BaseController
    {
        // GET: Administrators
        public ActionResult Index()
        {
            return View();
        }
        public async Task<ActionResult> News()
        {
            InitiateConfig();
            var news = await db.News.Include("Author")
                .Include("Category").Where(x => x.IsDeleted == false)
                .ToListAsync();
            return View(news);
        }
        public async Task<ActionResult> NewsPublished()
        {
            InitiateConfig();
            var news = await db.News.Include("Author")
                .Include("Category").Where(x => x.IsDeleted == false && x.Status == Status.Published)
                .ToListAsync();
            return View(news);
        }
        [HttpGet]
        public async Task<ActionResult> NewsDetail(string permalink)
        {
            InitiateConfig();
            if (permalink == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var news = await db.News.Include("Author")
                .Include("Category").Where(x => x.Permalink == permalink)
                .SingleOrDefaultAsync();
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }
        [HttpPost]
        public async Task<ActionResult> NewsDelete(string permalink)
        {
            if (permalink == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var news = await db.News.Include("Author")
                .Include("Category").Where(x => x.Permalink == permalink)
                .SingleOrDefaultAsync();
            if (news == null)
            {
                return HttpNotFound();
            }
            else
            {
                news.IsDeleted = true;
                news.Updated = DateTimeOffset.Now;
                var result = await db.SaveChangesAsync();
                if(result > 0)
                    return RedirectToAction("News");
            }
            return RedirectToAction("NewsDetail", new { permalink = news.Permalink });
        }
        [HttpPost]
        public async Task<ActionResult> NewsApprove(string permalink)
        {
            if (permalink == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var adminUser = await db.Staffs.Where(x => x.UserName == User.Identity.Name)
                .SingleOrDefaultAsync();
            var news = await db.News.Include("Author")
                .Include("Category").Where(x => x.Permalink == permalink)
                .SingleOrDefaultAsync();
            if (news == null)
            {
                return HttpNotFound();
            }
            else
            {
                news.Status = Status.Published;
                news.Updated = DateTimeOffset.Now;
                news.Author.Balance += news.Price;
                var newsTransaction = new NewsTransaction()
                {
                    News = news,
                    Staff = adminUser,
                    Approved = DateTimeOffset.Now,
                    IdTransaction = Guid.NewGuid().ToString(),
                    Writer = news.Author,
                    Price = news.Price
                };
                db.NewsTransactions.Add(newsTransaction);
                var result = await db.SaveChangesAsync();
                if (result > 0)
                    return RedirectToAction("News");
            }
            return RedirectToAction("NewsDetail", new { permalink = news.Permalink });
        }
    }
}

BootPress/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BootPress.Models;
using BootPress.ViewModels;

namespace BootPress.Controllers
{
    [Authorize(Roles = "Author, Administrator")]
    public class NewsController : BaseController
    {
       
        // GET: News
        public async Task<ActionResult> Index()
        {
            //var currentUser = await db.Users.Where(x => x.UserName == User.Identity.Name)
            //    .SingleOrDefaultAsync();
            InitiateConfig();
            var news = await db.News.Include("Author")
                .Include("Category").Where(x => x.Author.UserName == User.Identity.Name)
                .ToListAsync();
            return View(news);
        }

        // GET: News/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = await db.News.FindAsync(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }
        [Authorize]
        // GET: News/Create
        public async Task<ActionResult> Create()
        {
            InitiateConfig();
            var categories = await db.Categories.OrderBy(x => x.Name)
                .Select(i => new SelectListItem()
                {
                    Text = i.Name,
                    Value = i.IdCategory,
                    Selected = false
                }).ToArrayAsync();
            ViewBag.Categories = categories;
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AddNews news)
        {
            if (ModelState.IsValid)
            {
                news.Permalink = news.Title.Replace(" ", "-")
                    .Replace("&","").ToLower();
                var user = await db.Users.Where(x => x.UserName == User.Identity.Name)
                    .SingleOrDefaultAsync();
                if(user != null)
                {
                    var addNews = new News();
                    addNews.Author = user;
                    addNews.Permalink = news.Permalink;
                    addNews.Content = news.Content;
                    addNews.Hightlight = news.Hightlight;
                    addNews.Status = Status.Draft;
                    addNews.Created = DateTimeOffset.Now;
                    addNews.Price = news.Price;
                    addNews.Title = news.Title;
                    var newsCategory = await db.Categories.FindAsync(news.Category);
                    if (newsCategory != null)
                    {
                        addNews.Category = newsCategory;
                        db.News.Add(addNews);
                        var result = await db.SaveChangesAsync();
                        if (result > 0)
                            return RedirectToAction("Index");
                    }
                }
                
            }
            var categories = await db.Categories.OrderBy(x => x.Name)
                .Select(i => new SelectListItem()
                {
                    Text = i.Name,
                    Value = i.IdCategory,
                    Selected = false
                }).ToArrayAsync();
            ViewBag.Categories = categories;
            return View(news);
        }

        // GET: News/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var news = await db.News.Include("Author")
                .Include("Category").Where(x => x.Permalink == id)
                .SingleOrDefaultAsync();
            if (news == null)
            {
                return HttpNotFound();
            }
            var categories = await db.Categories.OrderBy(x => x.Name)
                .Select(i => new SelectListItem()
                {
                    Text = i.Name,
                    Value = i.IdCategory,
                    Selected = false
                }).ToArrayAsync();
            foreach(var item in categories)
            {
                if (item.Value.Equals(news.Category.IdCategory))
                {
                    item.Selected = true;
                    break;
                }   
            }
            ViewBag.Categories = categories;
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(UpdateNews news)
        {
            if (ModelState.IsValid)
            {
                var currentNews = await db.News.Include("Category")
                    .Where(x => x.Permalink == news.Permalink)
                    .SingleOrDefaultAsync();
                currentNews.Title = news.Title;
                currentNews.Hightlight = news.Hightlight;
                currentNews.Content = news.Content;
                currentNews.Status = news.Status;
                if(!currentNews.Category.IdCategory.Equals(news.Category))
                {
                    var newCategory = await db.Categories.FindAsync(news.Category);
                    if(newCategory != null)
                    {
                        currentNews.Category = newCategory;
                    }
                }
                var result = await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(news);
        }

        // GET: News/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = await db.News.FindAsync(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            News news = await db.News.FindAsync(id);
            db.News.Remove(news);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BootPress/Views/Administrators/News.cshtml
@model IEnumerable<BootPress.Models.News>

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Index";
}
<div class="row page-titles">
    <div class="col-md-6 col-8 align-self-center">
        <h3 class="text-themecolor m-b-0 m-t-0">News Management</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">News</a></li>
            <li class="breadcrumb-item active">Daftar Berita</li>
        </ol>
    </div>
    <div class="col-md-6 col-4 align-self-center">

    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"><a href="@Url.Action("Create","News")" class="btn btn-info btn-rounded">Tambahkan Berita</a></h4>
                <div class="table-responsive m-t-40">
                    <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Judul Berita</th>
                                <th>Kategori</th>
                                <th>Penulis</th>
                                <th>Tanggal</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Judul Berita</th>
                                <th>Kategori</th>
                                <th>Penulis</th>
                                <th>Tanggal</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Title</td>
                                    <td>@item.Category.Name</td>
                                    @{
                                        if (item.Author != null)
                                        {
                                            <td>@item.Author.FullName</td>
                                        }
                                        else
                                        {
                                            <td>Tidak Ada Penulis</td>
                                        }
                                    }
                                    <td>@item.Created.ToString("dd-MM-yyyy hh:mm")</td>
                                    <td>
                                        <a href="@Url.Action("NewsEdit","Administrators", new { permalink = @item.Permalink })" data-toggle="tooltip" data-original-title="Edit"> <i class="fa fa-pencil text-inverse m-r-10"></i> </a>
                                        <a href="@Url.Action("NewsDetail","Administrators", new { permalink = @item.Permalink })" data-toggle="tooltip" data-original-title="Detail"> <i class="fa fa-globe text-danger"></i> </a>
                                    </td>
                                </tr>
                                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

BootPress/Views/Administrators/NewsDetail.cshtml
@model BootPress.Models.News
@{
    ViewBag.Title = "NewsDetail";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="row page-titles">
    <div class="col-md-6 col-8 align-self-center">
        <h3 class="text-themecolor m-b-0 m-t-0">News</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
            <li class="breadcrumb-item">News</li>
            <li class="breadcrumb-item active">@Model.Title</li>
        </ol>
    </div>
    <div class="col-md-6 col-4 align-self-center">

    </div>
</div>
<!-- ============================================================== -->
<!-- End Bread crumb and right sidebar toggle -->
<!-- ============================================================== -->
<!-- ============================================================== -->
<!-- Start Page Content -->
<!-- ============================================================== -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h1>@Model.Title</h1>
                <p>Author @Model.Author.FullName</p>
                <p>@Model.Created.ToString("dd-mm-yyyy hh:mm")</p>
                <p>Kategori: @Model.Category.Name</p>
                <p>Harga: @Model.Price</p>
                @Html.Raw(HttpUtility.HtmlDecode(Model.Content))
                @using (Html.BeginForm("NewsDelete", "Administrators", null, FormMethod.Post, new { @class = "form-horizontal m-t-40" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Permalink)
                    <div class="form-group">
                        <input type="submit" value="Hapus" class="btn btn-danger" />
                    </div>
                }
                @using (Html.BeginForm("NewsApprove", "Administrators", null, FormMethod.Post, new { @class = "form-horizontal m-t-40" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Permalink)
                    <div class="form-group">
                        <input type="submit" value="Approve" class="btn btn-primary" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

BootPress/Views/Administrators/NewsPublished.cshtml
@model IEnumerable<BootPress.Models.News>

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    ViewBag.Title = "Index";
}
<div class="row page-titles">
    <div class="col-md-6 col-8 align-self-center">
        <h3 class="text-themecolor m-b-0 m-t-0">News Management</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javascript:void(0)">News</a></li>
            <li class="breadcrumb-item active">Daftar Berita</li>
        </ol>
    </div>
    <div class="col-md-6 col-4 align-self-center">

    </div>
</div>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"><a href="@Url.Action("Create","News")" class="btn btn-info btn-rounded">Tambahkan Berita</a></h4>
                <div class="table-responsive m-t-40">
                    <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Judul Berita</th>
                                <th>Kategori</th>
                                <th>Penulis</th>
                                <th>Tanggal</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Judul Berita</th>
                                <th>Kategori</th>
                                <th>Penulis</th>
                                <th>Tanggal</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Title</td>
                                    <td>@item.Category.Name</td>
                                    @{
                                        if (item.Author != null)
                                        {
                                            <td>@item.Author.FullName</td>
                                        }
                                        else
                                        {
                                            <td>Tidak Ada Penulis</td>
                                        }
                                    }
                                    <td>@item.Created.ToString("dd-MM-yyyy hh:mm")</td>
                                    <td>
                                        <a href="@Url.Action("NewsEdit","Administrators", new { permalink = @item.Permalink })" data-toggle="tooltip" data-original-title="Edit"> <i class="fa fa-pencil text-inverse m-r-10"></i> </a>
                                        <a href="@Url.Action("NewsDetail","Administrators", new { permalink = @item.Permalink })" data-toggle="tooltip" data-original-title="Detail"> <i class="fa fa-globe text-danger"></i> </a>
                                    </td>
                                </tr>
                                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts
{
<script src="~/Content/assets/admin/plugins/datatables/jquery.dataTables.min.js"></script>
<!-- start - This is for export functionality only -->
<script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
<!-- end - This is for export functionality only -->
<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
        $(document).ready(function () {
            var table = $('#example').DataTable({
                "columnDefs": [{
                    "visible": false,
                    "targets": 2
                }],
                "order": [
                    [2, 'asc']
                ],
                "displayLength": 25,
                "drawCallback": function (settings) {
                    var api = this.api();
                    var rows = api.rows({
                        page: 'current'
                    }).nodes();
                    var last = null;
                    api.column(2, {
                        page: 'current'
                    }).data().each(function (group, i) {
                        if (last !== group) {
                            $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                            last = group;
                        }
                    });
                }
            });
            // Order by the grouping
            $('#example tbody').on('click', 'tr.group', function () {
                var currentOrder = table.order()[0];
                if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                    table.order([2, 'desc']).draw();
                } else {
                    table.order([2, 'asc']).draw();
                }
            });
        });
    });
    $('#example23').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    });
</script>
}